### PR TITLE
Throwing Snowballs

### PR DESCRIPTION
**Pull request by erokasyuart**
# Overview

- Player presses 'Q', a snowball will instantiate at the player's head level and constantly move forward until it collides with anything that has a rigidbody (other snowballs, walls, etc).
- There is no player rotation script because I assume that's being done in a player movement branch. Rotating the player in the scene, the snowballs will still instantiate and move in front of the player.
- I didn't include a second player's snowball as I don't know the best way to incorporate it.

### CODE REVIEW

**Comment by PBWiseman** [comment]
Is this pull request ready for reviews?

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Feature is functional and throwing and destroying both work well. Snowball position should be set in the throw snowball function not in start so that it updates when the player moved side to side not just turns. The turning and snowball movement both work well. The code currently uses the old input system but the new one is set up in the staging branch currently so it should be quick to change that over once merged. You don't need to worry about the second player as the same script can be on both players and the new input system will take care of changing the inputs to the correct ones.

Once the positioning issue is solved, I am happy for this to be merged!

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
Throwing snowballs is functional and from testing i can see it changes direction as needed. The only issue that i can see is that if the player is moved in the scene. the snowball doesn't account for the new position and is instantiated at the original position.  

Your scripts are well commented and easy to follow so once that issue is sorted this will be ready to merge

**Review by ChaseBENNC9 — APPROVED** [review]
Concern addressed. your branch is approved to be merge.

**Review by PBWiseman — APPROVED** [review]
Concern addressed. Approved to merge.

**Pull request merged**
