### PR TITLE
Snow Production

### PR DESCRIPTION
**Pull request by erokasyuart**
## Describe your changes

The snow machine slowly produces snowballs for the snow tray. The player can interact with the snow machine by holding 'E' to speed up production.

Scene - `SnowAmmo 2`
Scripts - All in Snowball folder

#47 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by erokasyuart** [comment]
I didn;t mean to undraft or request reviews yet sorry, got the branches mixed up

**Review by PBWiseman — CHANGES_REQUESTED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Both interactions work correctly.

## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - If you stand in between the two objects you can interact with both of them at the same time.
 - You can still collect from the tray even though you have max snowballs

***

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Functionally the snowball machine is working. the bars looks great


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Happy with formatting and comments 




## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - As we discussed the snowball machine may work better if its reducing by 5 rather than 1 as it makes more sense in the context of the player receiving 5 snowballs

- there is an issue were you can interact with both the pile and the machine at the same time probably just needs a smaller trigger collider

- As you saw sometimes the player movement triggers the loading bar. It seems to jump back and forward. really strange bug

## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_

**Comment by erokasyuart** [comment]
## Changes Made
- Sensible amount of snowballs can be taken on a tray depending on how much the player has and how much the tray has.
  - The meter won't show up if you have the maximum ammo.
  - If both the player and the tray have less than the max snowballs, it will do the math to give you the maximum allowed amount.
- A second machine has been added to simulate multiple in the future.
   - Code has been rearranged and rewritten to support multiple machines and to work independently.
      - Also limited the use of GameObject.Find()! If find is used, it's often in it's own children, or else GetChild()[] is used.
- Replaced debug log for in-game worldspace text for the snow tray's inventory.
- The snow machine will stop producing snowballs when the amount in the tray reaches (currently) 15 snowballs to stop an infinite amount.
   - The meter will also disappear to show that it has halted production.

**Review by ChaseBENNC9 — COMMENTED** [review]
**Bugs**
There was still the bug where the Slider UI elements were tracking player movement, but I believe I have found a solution to this.  On the snowball machine prefab navigate to
`Snowball Machine > Canvas > Progress ` 
Navigate to the Slider Component. and on the Navigation of the slider this needs to be changed to None.  
Should also do this on 
`Snow Tray > Canvas > Progress`
image

The issue was caused by the second player because when the button is selected the navigation allows the selected UI element to change to the slider. and then the arrow keys and for some reason WASD would control it

**Review by ChaseBENNC9 — APPROVED** [review]
All previous issues have been resolved,  your refactored code reads well and everything is formatted nicely I am happy with this to be merged

**Review by PBWiseman — APPROVED** [review]

**Pull request merged**
