### PR TITLE
Player Movement

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

The player will be able to move in 8 directions around the play space. They will be blocked by the edge and by other entities such as the second player or enemies. This will use the unity input system to be able to reuse the movement code for 2 players on the same keyboard.

## Issue number and link

#4 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by PBWiseman** [comment]
Movement
Two players can move. It will also select a penguin prefab. There is an ENUM and a global static variable to select them. If none are selected, then it will select a random one. I still need to implement turning and then once that is done, I will likely start on related things like p2 hot joining.

**Comment by PBWiseman** [comment]
Movement code is ready for testing. The two prefabs spawned in move with WASD and Arrow Keys. I am going to add hot joining in a subbranch as it is a separate feature

**Review by ChaseBENNC9 — COMMENTED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Yes the player is able to be moved with WASD and player 2 with directional arrows. Movement is smooth and no collision issues were found


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Code is well commented and structured, easy to follow

_Any repetitive code that could be refactored? (DRY)_  

 - Code is all dry


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Everything is functional, although I noticed the players are able to push eachother around. Is this intentional or could there be a way to avoid this happening?

 I like the movement and player spawning looks great. 
# Final Comments

 -  Only thing was whether the players should be able to push each other around and that could possibly come up in a discussion. Movement feels great and didn't notice any bugs from it. 
 - Once a decision is made i will update my Review

***

**Review by ChaseBENNC9 — APPROVED** [review]
Discussion about player movement determined that it was a  low priotity to find a work around the players moving eachother around

**Review by erokasyuart — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Yes. Player(s) spawn and move.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Well explained

_Any repetitive code that could be refactored? (DRY)_  

 - Not that I could improve on.


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Yes. Random type works too.


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - Fine.


# Final Comments

 - Can the player actually slide? or is the code just for future.

***

**Comment by PBWiseman** [comment]
> Can the player actually slide? or is the code just for future.

The sliding is implemented in #17 !

**Pull request merged**
