### PR TITLE
Snowball Animation Position

### PR DESCRIPTION
**Pull request by erokasyuart**
## Describe your changes

All penguins, kangaroos and joeys throw snowballs from their flipper mid-animation. This is done through setting an animation event at a specific frame in the animation to call a method.
Some of the animation names had to be changed for the right parameters for the method called.
Hopefully I removed any changes in the main scene, but I was testing there, but most changes were focused on prefabs.

Scripts changed: `ThrowSnowballs.cs`

## Issue number and link

- #83 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by PBWiseman — CHANGES_REQUESTED** [review]
The Kangaroo and Joey animations look great! Couple of small changes for the penguin one. Can you untick has exit time on the Movement Blend > Throw transition so it starts throwing right away and doesn't wait for the current movement time to end. The only other thing is that the player can spam the throw key and deplete their inventory while the first snowball is still being thrown. Can there be a lockout on throwing until the animation is done to stop this from happening?

**Review by ChaseBENNC9 — APPROVED** [review]
Changes look great, you've done a great job implementing the animations
I agree with palin in that it would look better if the players animation wasn't delayed so much other than that good to merge

**Comment by erokasyuart** [comment]
> The Kangaroo and Joey animations look great! Couple of small changes for the penguin one. Can you untick has exit time on the Movement Blend > Throw transition so it starts throwing right away and doesn't wait for the current movement time to end. The only other thing is that the player can spam the throw key and deplete their inventory while the first snowball is still being thrown. Can there be a lockout on throwing until the animation is done to stop this from happening? The position and timing of throwing look great though.

Where is this? I found mute and solo checkboxes in the animator but they're all already unchecked.

**Comment by PBWiseman** [comment]
> > The Kangaroo and Joey animations look great! Couple of small changes for the penguin one. Can you untick has exit time on the Movement Blend > Throw transition so it starts throwing right away and doesn't wait for the current movement time to end. The only other thing is that the player can spam the throw key and deplete their inventory while the first snowball is still being thrown. Can there be a lockout on throwing until the animation is done to stop this from happening? The position and timing of throwing look great though.
> 
> Where is this? I found mute and solo checkboxes in the animator but they're all already unchecked.

image
Click on the blue highlighted line in the penguin animator and then untick has exit time

**Review by PBWiseman — APPROVED** [review]

**Pull request merged**
