### PR TITLE
Snowball Slam v1.2.0

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
Changelog
-
- ADD: Enviromental Hazard: Hot Road
- ADD: Enemy Ability: Joey

Visual Updates
-
- VISUAL: (TBD)

Bug fixes
-
- FIX: Player Moving after End Game
- FIX: Enemy Moving after End Game
- FIX: Friendly Fire 
- FIX: Throwing Snowballs while Sliding

Known bugs
- 
- BUG: (TBD)

Background Improvements
-
- IMPROVE: Removed old Level Files

### CODE REVIEW

**Comment by PBWiseman** [comment]
Issues:
Sliding is floating in mid air
Snowball throwing isn't fully hooked up yet. Needs to have an animation trigger and a new release point
Snowball machine needs a collider
Kangaroos need better logic about throwing snowballs
The hopping animation looks weird with the throwing one and with turning. Maybe make it so they have to stop to throw?
Joey despawning needs to be triggered by the animation not instant
Joey thinks everywhere is blocked so never gets placed
Endgame Spawnpoints and camera are not set up properly

**Comment by PBWiseman** [comment]
Heat distortion should ramp up in intensity

**Comment by ChaseBENNC9** [comment]
More issues:
Sliding is floating in mid air
Snowball throwing isn't fully hooked up yet. Needs to have an animation trigger and a new release point
Snowball machine needs a collider
Kangaroos need better logic about throwing snowballs
The hopping animation looks weird with the throwing one and with turning. Maybe make it so they have to stop to throw?
~Joey despawning needs to be triggered by the animation not instant~
~Joey thinks everywhere is blocked so never gets placed~
Endgame Spawnpoints and camera are not set up properly

**Review by erokasyuart — APPROVED** [review]

**Comment by PBWiseman** [comment]
More issues:
Heat haze doesn't ramp up
Heat haze is over penguins and it doesn't look great.
Snowball throwing really jank
Animations of characters in endgame keep playing

**Comment by PBWiseman** [comment]
Snowballs need to be fixed
Changes resolution and settings on restart reset
Collider right down the middle of the bottom road
Need snowball count
Right side machine snowball count
No snowball throwing animation

Later fixes:
More obvious for the road slowing
Colliders need to be the same width

**Comment by PBWiseman** [comment]
Controls aren't great
19 10 screen res cuts off the right side of screen

**Pull request merged**
